DROP DATABASE HUCO_EXPENSE_TRACKING;

CREATE DATABASE HUCO_EXPENSE_TRACKING;
USE HUCO_EXPENSE_TRACKING;

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(50) NOT NULL UNIQUE,
    USER_PASSWORD VARCHAR(255) NOT NULL,
    USER_EMAIL VARCHAR(100) UNIQUE,
    USER_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);

DROP TABLE IF EXISTS CATEGORIES;
CREATE TABLE CATEGORIES (
    CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NULL,
    CATEGORY_NAME VARCHAR(50) NOT NULL,
    CATEGORY_TYPE ENUM('INCOME','EXPENSE') NOT NULL,
    CATEGORY_ICON VARCHAR(150),
    CATEGORY_COLOR VARCHAR(7),
    CATEGORY_IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CATEGORY_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CATEGORIES_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

DROP TABLE IF EXISTS TRANSACTIONS;
CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    CATEGORY_ID INT NULL,
    TRANSACTION_AMOUNT BIGINT NOT NULL CHECK (TRANSACTION_AMOUNT > 0),
    TRANSACTION_DATE DATETIME NOT NULL,
    TRANSACTION_NOTE TEXT,
    TRANSACTION_IMAGE_URL VARCHAR(255),
    TRANSACTION_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_TRANSACTIONS_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_TRANSACTIONS_CATEGORIES FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID) ON DELETE SET NULL
);

-- Chưa dùng tới bảng này, dùng cho tính năng phát triển sau
DROP TABLE IF EXISTS BUDGETS; 
CREATE TABLE BUDGETS (
    BUDGET_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    CATEGORY_ID INT NOT NULL,
    BUDGET_AMOUNT_LIMIT DECIMAL(15,2) NOT NULL CHECK (BUDGET_AMOUNT_LIMIT > 0),
    BUDGET_MONTH INT NOT NULL CHECK (BUDGET_MONTH BETWEEN 1 AND 12),
    BUDGET_YEAR INT NOT NULL CHECK (BUDGET_YEAR >= 2020),
    BUDGET_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_BUDGETS_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_BUDGETS_CATEGORIES FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID) ON DELETE CASCADE
);

SELECT * FROM USERS;

DELETE FROM USERS WHERE USER_ID <> "";

-- Tài khoản mẫu 
INSERT INTO USERS (USER_NAME, USER_PASSWORD, USER_EMAIL)
VALUES ('Cuong Do Duc', 'abcd1234', 'doduccuong24102005@gmail.com');

-- Danh mục mẫu
INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_TYPE, CATEGORY_ICON, CATEGORY_COLOR, USER_ID) VALUES 
-- Chi tiêu (EXPENSE)
('Ăn uống', 'EXPENSE', 'utensils', '#FF6B6B', NULL),
('Di chuyển', 'EXPENSE', 'bus', '#4ECDC4', NULL),
('Mua sắm', 'EXPENSE', 'shopping-bag', '#FFE66D', NULL),
('Giải trí', 'EXPENSE', 'gamepad', '#1A535C', NULL),
('Tiền nhà', 'EXPENSE', 'home', '#FF9F1C', NULL),
('Điện nước', 'EXPENSE', 'bolt', '#FDD835', NULL),
('Sức khỏe', 'EXPENSE', 'medkit', '#FF4081', NULL),
('Xăng xe', 'EXPENSE', 'gas-pump', '#5D4037', NULL),
('Giáo dục', 'EXPENSE', 'graduation-cap', '#3F51B5', NULL),
('Làm đẹp', 'EXPENSE', 'spa', '#E91E63', NULL),
('Thú cưng', 'EXPENSE', 'paw', '#795548', NULL),
-- Thu nhập (INCOME)
('Lương', 'INCOME', 'money-bill-wave', '#2ECC71', NULL),
('Thưởng', 'INCOME', 'gift', '#F1C40F', NULL),
('Đầu tư', 'INCOME', 'chart-line', '#9B59B6', NULL),
('Lì xì', 'INCOME', 'envelope-open-text', '#E74C3C', NULL);
SELECT * FROM CATEGORIES;

-- Giao dịch mẫu
-- Xóa các giao dịch cũ của User 1 để nạp lại dữ liệu mới cho sạch
DELETE FROM TRANSACTIONS WHERE USER_ID = 1;
INSERT INTO TRANSACTIONS (USER_ID, CATEGORY_ID, TRANSACTION_AMOUNT, TRANSACTION_NOTE, TRANSACTION_DATE) VALUES 
-- --- TUẦN NÀY (Gần đây nhất) ---
(1, 1, 45000, 'Cà phê sáng Highlands', NOW()),
(1, 2, 28000, 'Grab đi làm', NOW()),
(1, 1, 120000, 'Ăn trưa với đồng nghiệp', DATE_SUB(NOW(), INTERVAL 1 DAY)),
(1, 3, 500000, 'Đi siêu thị mua đồ ăn vặt', DATE_SUB(NOW(), INTERVAL 2 DAY)),
(1, 8, 80000, 'Đổ xăng đầy bình', DATE_SUB(NOW(), INTERVAL 3 DAY)),
-- --- TUẦN TRƯỚC (7 - 14 ngày trước) ---
(1, 4, 220000, 'Vé xem phim cuối tuần', DATE_SUB(NOW(), INTERVAL 7 DAY)),
(1, 1, 350000, 'Lẩu nướng Haidilao', DATE_SUB(NOW(), INTERVAL 8 DAY)),
(1, 9, 250000, 'Mua sách lập trình Node.js', DATE_SUB(NOW(), INTERVAL 10 DAY)),
(1, 11, 150000, 'Mua hạt cho mèo', DATE_SUB(NOW(), INTERVAL 12 DAY)),
(1, 6, 1200000, 'Thanh toán tiền điện tháng này', DATE_SUB(NOW(), INTERVAL 14 DAY)),
-- --- THU NHẬP (Lương về giữa tháng) ---
(1, 12, 18000000, 'Nhận lương tháng', DATE_SUB(NOW(), INTERVAL 15 DAY)), -- ID 12 là Lương
(1, 14, 2500000, 'Lãi từ chứng khoán', DATE_SUB(NOW(), INTERVAL 16 DAY)), -- ID 14 là Đầu tư
-- --- 2-3 TUẦN TRƯỚC ---
(1, 5, 4500000, 'Đóng tiền nhà trọ', DATE_SUB(NOW(), INTERVAL 18 DAY)), -- Tiền nhà
(1, 10, 200000, 'Cắt tóc', DATE_SUB(NOW(), INTERVAL 20 DAY)),
(1, 2, 150000, 'Bắt taxi đi sân bay', DATE_SUB(NOW(), INTERVAL 22 DAY)),
(1, 3, 850000, 'Mua giày Adidas Sale', DATE_SUB(NOW(), INTERVAL 24 DAY)),
-- --- THÁNG TRƯỚC ( > 30 ngày, để test lọc tháng) ---
(1, 7, 300000, 'Khám sức khỏe định kỳ', DATE_SUB(NOW(), INTERVAL 32 DAY)),
(1, 13, 1000000, 'Thưởng KPI dự án', DATE_SUB(NOW(), INTERVAL 33 DAY)), -- ID 13 là Thưởng
(1, 1, 60000, 'Cơm tấm đêm khuya', DATE_SUB(NOW(), INTERVAL 35 DAY)),
(1, 4, 150000, 'Nạp game', DATE_SUB(NOW(), INTERVAL 38 DAY));
SELECT * FROM TRANSACTIONS;

