export const MATERIAL_COLORS = [
  "#F44336",
  "#E91E63",
  "#9C27B0",
  "#673AB7",
  "#3F51B5",
  "#2196F3",
  "#03A9F4",
  "#00BCD4",
  "#009688",
  "#4CAF50",
  "#8BC34A",
  "#CDDC39",
  "#FFEB3B",
  "#FFC107",
  "#FF9800",
  "#FF5722",
  "#795548",
  "#9E9E9E",
  "#607D8B",
  "#2c3e50",
];

export const AVAILABLE_ICONS = [
  "star",
  "heart",
  "home",
  "user",
  "smile",
  "frown",
  "bell",
  "lock",
  "utensils",
  "hamburger",
  "pizza-slice",
  "coffee",
  "wine-glass",
  "beer",
  "birthday-cake",
  "carrot",
  "apple-alt",
  "car",
  "bus",
  "motorcycle",
  "bicycle",
  "plane",
  "gas-pump",
  "parking",
  "walking",
  "shopping-bag",
  "shopping-cart",
  "tshirt",
  "gamepad",
  "music",
  "film",
  "camera",
  "ticket-alt",
  "gift",
  "baby-carriage",
  "paw",
  "dog",
  "cat",
  "couch",
  "bed",
  "bath",
  "broom",
  "tools",
  "briefcase",
  "laptop",
  "mobile-alt",
  "wifi",
  "bolt",
  "water",
  "file-invoice-dollar",
  "credit-card",
  "piggy-bank",
  "medkit",
  "pills",
  "dumbbell",
  "running",
  "swimmer",
  "football-ball",
  "basketball-ball",
  "graduation-cap",
  "book",
  "pen",
  "globe",
  "cloud-sun",
  "umbrella",
];

export const EXPENSE_CATEGORIES = [
  { id: 1, name: "Ăn uống", icon: "utensils", color: "#FF6B6B" },
  { id: 2, name: "Di chuyển", icon: "bus", color: "#4ECDC4" },
  { id: 3, name: "Mua sắm", icon: "shopping-bag", color: "#FFE66D" },
  { id: 4, name: "Giải trí", icon: "gamepad", color: "#1A535C" },
  { id: 5, name: "Tiền nhà", icon: "home", color: "#FF9F1C" },
  { id: 6, name: "Điện nước", icon: "bolt", color: "#FDD835" },
  { id: 7, name: "Sức khỏe", icon: "medkit", color: "#FF4081" },
  { id: 8, name: "Xăng xe", icon: "gas-pump", color: "#5D4037" },
  { id: 9, name: "Giáo dục", icon: "graduation-cap", color: "#3F51B5" },
  { id: 10, name: "Làm đẹp", icon: "spa", color: "#E91E63" },
  { id: 11, name: "Thú cưng", icon: "paw", color: "#795548" },
  { id: 12, name: "Du lịch", icon: "plane", color: "#03A9F4" },
  { id: 13, name: "Liên lạc", icon: "mobile-alt", color: "#607D8B" },
  { id: 14, name: "Con cái", icon: "baby-carriage", color: "#9C27B0" },
];

export const INCOME_CATEGORIES = [
  { id: 101, name: "Lương", icon: "money-bill-wave", color: "#4CAF50" },
  { id: 102, name: "Thưởng", icon: "gift", color: "#FF9800" },
  { id: 103, name: "Đầu tư", icon: "chart-line", color: "#2196F3" },
  { id: 104, name: "Bán hàng", icon: "store", color: "#9C27B0" },
  { id: 105, name: "Cho thuê", icon: "key", color: "#795548" },
  { id: 106, name: "Lãi tiết kiệm", icon: "piggy-bank", color: "#E91E63" },
];
