/**
 * FILE: Color_Icon.js
 * VAI TRÒ: Kho tài nguyên tĩnh (Static Resources)
 * 1. MATERIAL_COLORS: Bảng mã màu dùng cho danh mục.
 * 2. AVAILABLE_ICONS: Danh sách tên icon (FontAwesome5) hỗ trợ.
 */

// Bảng màu Material Design (Dùng random khi tạo danh mục mới)
export const MATERIAL_COLORS = [
  "#F44336",
  "#E91E63",
  "#9C27B0",
  "#673AB7",
  "#3F51B5",
  "#2196F3",
  "#03A9F4",
  "#00BCD4",
  "#009688",
  "#4CAF50",
  "#8BC34A",
  "#CDDC39",
  "#FFEB3B",
  "#FFC107",
  "#FF9800",
  "#FF5722",
  "#795548",
  "#9E9E9E",
  "#607D8B",
  "#2c3e50",
];

// Danh sách Icon hỗ trợ hiển thị (Để người dùng chọn)
export const AVAILABLE_ICONS = [
  "star",
  "heart",
  "home",
  "user",
  "smile",
  "frown",
  "bell",
  "lock",
  "utensils",
  "hamburger",
  "pizza-slice",
  "coffee",
  "wine-glass",
  "beer",
  "birthday-cake",
  "carrot",
  "apple-alt",
  "car",
  "bus",
  "motorcycle",
  "bicycle",
  "plane",
  "gas-pump",
  "tools",
  "wrench",
  "hammer",
  "school",
  "graduation-cap",
  "book",
  "pen",
  "globe",
  "cloud-sun",
  "umbrella",
  "gamepad",
  "music",
  "film",
  "camera",
  "shopping-bag",
  "shopping-cart",
  "gift",
  "credit-card",
  "money-bill-wave",
  "wallet",
  "piggy-bank",
  "chart-line",
  "chart-pie",
  "briefcase",
  "building",
  "hospital",
  "medkit",
  "pills",
  "stethoscope",
  "first-aid",
  "paw",
  "dog",
  "cat",
  "fish",
  "tshirt",
  "socks",
  "shoe-prints",
  "glasses",
  "mobile-alt",
  "laptop",
  "desktop",
  "tv",
  "wifi",
  "battery-full",
  "bolt",
];
